# This action creates downstream PRs for PRs with backport labels defined.
# See docs here: https://github.com/hashicorp/backport-assistant

name: Backport Assistant Runner

on:
  # TODO: Figure out if this should be `pull_request_target` if we have forks.
  pull_request:
    types:
      - closed
      - labeled

jobs:
  backport:
    if: github.event.pull_request.merged
    runs-on: ubuntu-latest
    container: hashicorpdev/backport-assistant:0.2.3
    steps:
      - name: Run Backport Assistant
        # Update this to auto-merge when we have confidence in the process working and kill Circle
        run: |
          backport-assistant backport -merge-method=rebase
        env:
          BACKPORT_LABEL_REGEXP: "backport\/(?P<target>\\d+\\.\\d+)"
          BACKPORT_TARGET_TEMPLATE: "release/{{.target}}.x"
          GITHUB_TOKEN: ${{ secrets.ELEVATED_GITHUB_TOKEN }}
  
  # TODO: Move cherry-pick job for website here
